#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset
# estas variables indican que si hay algun error se escale hasta arriba(frontend?)


python manage.py migrate
python manage.py runserver 0.0.0.0:8000

# asi es como correriamos normalmente nuestra aplicacion
# lanzamos el migrate para aplicar los cambios en nuestra DB
# runserver indica que para todo el mundo se usa el puerto 8000
