# Generated by Django 3.1.1 on 2020-11-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on wich the object was last modified', verbose_name='modified at')),
                ('name', models.CharField(max_length=140, verbose_name='circle name')),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('about', models.CharField(max_length=255, verbose_name='circles description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='circles/pictures/')),
                ('rides_offered', models.PositiveIntegerField(default=0)),
                ('rides_taken', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False, help_text='verificacion de circulos oficiales de la pagina', verbose_name='verified circle')),
                ('is_public', models.BooleanField(default=True, help_text='listado de circulos publicos para acceder')),
                ('is_limited', models.BooleanField(default=False, help_text='limite de miembros por este circulo', verbose_name='limited')),
                ('member_limit', models.PositiveIntegerField(default=0, help_text='este circulo esta limitado por una cantidad de miembros')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
