# Generated by Django 3.1.1 on 2020-11-11 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_auto_20201109_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='circles',
            new_name='circle',
        ),
    ]
