# Generated by Django 3.1.1 on 2020-11-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_auto_20201111_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='is_activate',
            field=models.BooleanField(default=False, help_text='only active users are allowed to interactive in the circle', verbose_name='active status'),
        ),
    ]
